src/TwigDeclensionBundle/Entity/Declension.php
<?php

namespace Bubnov\TwigDeclensionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Declension
 *
 * @ORM\Table(name="declension",
 * indexes={
 *  @ORM\Index(name="index_infinitive", columns={"infinitive"})
 * })
 * @ORM\Entity(repositoryClass="Bubnov\TwigDeclensionBundle\Entity\Repository\DeclensionRepository")
 */
class Declension
{
    /**
     * @var string
     */
    const INFINITIVE = 'inf';
    
    /**
     * @var string
     */
    const MULTI = 'inf_multi';
    
    /**
     * @var string
     */
    const GENITIVE = 'gen';
    
    /**
     * @var string
     */
    const GENITIVE_PLURAL = 'gen_multi';
    
    /**
     * @var string
     */
    const DATIVE = 'dat';
    
    /**
     * @var string
     */
    const ACCUSATIVE = 'acc';
    
    /**
     * @var string
     */
    const ABLATIVE = 'abl';
    
    /**
     * @var string
     */
    const PREPOSITIONAL = 'pre';
    
    /**
     * @var string
     */
    const PLURAL = 'plural';
    
    /**
     * Avalible forms
     * @var array
     */
    static public $forms = [
        self::INFINITIVE => 'infinitive',
        self::MULTI => 'multi',
        self::GENITIVE => 'genitive',
        self::GENITIVE_PLURAL => 'genitive_plural',
        self::DATIVE => 'dative',
        self::ACCUSATIVE => 'accusative',
        self::ABLATIVE => 'ablative',
        self::PREPOSITIONAL => 'prepositional',
        self::PLURAL => 'plural',
    ];
    
    /**
     * @var integer
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=false, unique=true)
     */
    private $infinitive;
    
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $genitive;
    
    
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $genitive_plural;
    
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $dative;
    
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $accusative;
    
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ablative;
    
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prepositional;
    
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $multi;

    /**
     *
     * @return string
     */
    public function __toString()
    {
        return $this->getInfinitive();
    }
    
    /**
     *
     * @param string $form
     * @return boolean
     */
    public function hasForm($form = self::INFINITIVE)
    {
        return isset(self::$forms[$form]);
    }
    
    /**
     *
     * @param string $form
     * @return string
     */
    public function getForm($form = self::INFINITIVE, $count = null)
    {
        if ($this->hasForm($form)) {
            $method = 'get' . ucfirst(self::$forms[$form]);

            if ($declensioned = $this->$method($count)) {
                return $declensioned;
            }
        }
        
        return $this->getInfinitive();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set infinitive
     *
     * @param string $infinitive
     * @return Declension
     */
    public function setInfinitive($infinitive)
    {
        $this->infinitive = $infinitive;

        return $this;
    }

    /**
     * Get infinitive
     *
     * @return string
     */
    public function getInfinitive()
    {
        return $this->infinitive;
    }

    /**
     * Set genitive
     *
     * @param string $genitive
     * @return Declension
     */
    public function setGenitive($genitive)
    {
        $this->genitive = $genitive;

        return $this;
    }

    /**
     * Get genitive
     *
     * @return string
     */
    public function getGenitive()
    {
        return $this->genitive;
    }

    /**
     * Set dative
     *
     * @param string $dative
     * @return Declension
     */
    public function setDative($dative)
    {
        $this->dative = $dative;

        return $this;
    }

    /**
     * Get dative
     *
     * @return string
     */
    public function getDative()
    {
        return $this->dative;
    }

    /**
     * Set accusative
     *
     * @param string $accusative
     * @return Declension
     */
    public function setAccusative($accusative)
    {
        $this->accusative = $accusative;

        return $this;
    }

    /**
     * Get accusative
     *
     * @return string
     */
    public function getAccusative()
    {
        return $this->accusative;
    }

    /**
     * Set ablative
     *
     * @param string $ablative
     * @return Declension
     */
    public function setAblative($ablative)
    {
        $this->ablative = $ablative;

        return $this;
    }

    /**
     * Get ablative
     *
     * @return string
     */
    public function getAblative()
    {
        return $this->ablative;
    }

    /**
     * Set prepositional
     *
     * @param string $prepositional
     * @return Declension
     */
    public function setPrepositional($prepositional)
    {
        $this->prepositional = $prepositional;

        return $this;
    }

    /**
     * Get prepositional
     *
     * @return string
     */
    public function getPrepositional()
    {
        return $this->prepositional;
    }
    
    /**
     * Set multi
     *
     * @param string $multi
     * @return Declension
     */
    public function setMulti($multi)
    {
        $this->multi = $multi;

        return $this;
    }

    /**
     * Get multi
     *
     * @return string
     */
    public function getMulti()
    {
        return $this->multi;
    }
    
    /**
     * Get plural
     * @param integer $n
     * @return string
     */
    public function getPlural($n = null)
    {
        if (is_null($n) || !is_integer($n) || 1 === $n) {
            return $this->getInfinitive();
        }
        
        $forms = [
            $this->getInfinitive(),
            $this->getGenitive(),
            $this->getGenitivePlural(),
        ];

        // Magic!
        return ($n%10 == 1 && $n%100 != 11 ? $forms[0] : ($n%10 >= 2 && $n%10 <= 4 && ($n%100 < 10 || $n%100 >= 20))
            ? $forms[1]
            : $forms[2])
        ;
    }

    /**
     * Set genitive_plural
     *
     * @param string $genitivePlural
     * @return Declension
     */
    public function setGenitivePlural($genitivePlural)
    {
        $this->genitive_plural = $genitivePlural;

        return $this;
    }

    /**
     * Get genitive_plural
     *
     * @return string
     */
    public function getGenitivePlural()
    {
        return $this->genitive_plural;
    }
    
    /**
     * @return boolean
     */
    public function isNeedWork()
    {
        foreach (self::$forms as $form) {
            if (empty($this->$form) && $form !== 'plural') {
                return true;
            }
        }
        
        return false;
    }
}

src/TwigDeclensionBundle/Form/Type/DeclensionType.php
<?php

namespace Bubnov\TwigDeclensionBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Bubnov\TwigDeclensionBundle\Entity\Declension;

class DeclensionType extends AbstractType
{
    const FORM_NAME = 'bubnovkelnik_twigdeclensionbundle_declension';

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        foreach (Declension::$forms as $form => $fullForm) {
            if (Declension::PLURAL === $form) {
                continue;
            }

            $required = (Declension::INFINITIVE === $form);

            $builder->add($fullForm, null, [
                'label' => 'twig-declension.forms.' . $form,
                'required' => $required,
                'attr' => ['twig-declension-form' => $form],
            ]);
        }
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Declension::class,
            'method'     => 'POST',
        ]);
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return self::FORM_NAME;
    }
}

src/TwigDeclensionBundle/Controller/DeclensionController.php
<?php

namespace Bubnov\TwigDeclensionBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Form\FormError;
use Doctrine\DBAL\DBALException;

use Bubnov\TwigDeclensionBundle\Entity\Declension;
use Bubnov\TwigDeclensionBundle\Form\Type\DeclensionType;
use Bubnov\TwigDeclensionBundle\Form\Type\FilterDeclensionFormType;

/**
 * Declension controller.
 * @Route("/admin/declension")
 * @Security("has_role('ROLE_ADMIN')")
 */
class DeclensionController extends Controller
{
    /**
     * Lists all Declension entities.
     *
     * @Route("/", name="admin_twig_declension")
     * @Template()
     */
    public function indexAction(Request $request)
    {
        $form = $this->createForm(FilterDeclensionFormType::class);
        $form->handleRequest($request);
        
        $em = $this->getDoctrine()->getManager();
        $qb = $em->getRepository(Declension::class)->getListQB($form->getData());

        $page = $request->query->get('page', 1);
        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $qb,
            $page,
            20
        );

        return [
            'pagination' => $pagination,
            'entities' => $pagination,
            'form' => $form->createView(),
        ];
    }
    
    /**
     * Creates a new Declension entity.
     *
     * @Route("/new", name="admin_twig_declension_new")
     * @Template("BubnovTwigDeclensionBundle:Declension:new.html.twig")
     */
    public function newAction(Request $request)
    {
        $entity = new Declension();
        $form = $this->createForm(DeclensionType::class, $entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            try {
                $em->persist($entity);
                $em->flush();
                $this->get('session')->getFlashBag()->add('success', 'twig-declension.added');

                return $this->redirectToRoute('admin_twig_declension');
            } catch (DBALException $e) {
                $error = new FormError($this->get('translator')->trans('twig-declension.errors.already_exist'));
                $form->get('infinitive')->addError($error);
            } catch (\Exception $e) {
                $error = new FormError($this->get('translator')->trans('twig-declension.errors.unknown_error'));
                $form->get('infinitive')->addError($error);
            }
        }

        return [
            'entity' => $entity,
            'form'   => $form->createView(),
        ];
    }

    /**
     * Displays a form to edit an existing Declension entity.
     *
     * @Route("/{id}/edit", name="admin_twig_declension_edit")
     * @Template()
     */
    public function editAction(Request $request, Declension $entity)
    {
        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Declension entity.');
        }

        $form = $this->createForm(DeclensionType::class, $entity, ['method' => 'PUT']);
        $form->handleRequest($request);

        if ($form->isValid()) {
            try {
                $this->getDoctrine()->getManager()->flush();
                $this->get('session')->getFlashBag()->add('success', 'twig-declension.edited');

                return $this->redirectToRoute('admin_twig_declension');
            } catch (DBALException $e) {
                $error = new FormError($this->get('translator')->trans('twig-declension.already_exist'));
                $form->get('infinitive')->addError($error);
            } catch (\Exception $e) {
                $error = new FormError($this->get('translator')->trans('twig-declension.errors.unknown_error'));
                $form->get('infinitive')->addError($error);
            }
        }

        return [
            'entity' => $entity,
            'form'   => $form->createView(),
        ];
    }

    /**
     * Deletes a Declension entity.
     *
     * @Route("/{id}/delete", name="admin_twig_declension_delete")
     * @Template()
     */
    public function deleteAction(Request $request, Declension $entity)
    {
        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Declension entity.');
        }
        
        $form = $this->createDeleteForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            try {
                $em->remove($entity);
                $em->flush();
                $this->get('session')->getFlashBag()->add('success', 'twig-declension.deleted');

                return $this->redirectToRoute('admin_twig_declension');
            } catch (\Exception $e) {
                $error = new FormError($this->get('translator')->trans('twig-declension.errors.unknown_error'));
                $form->addError($error);
            }
        }

        return [
            'entity' => $entity,
            'form'   => $form->createView(),
        ];
    }

    /**
     * Lists all Declension entities.
     *
     * @Route("/guess", name="admin_twig_declension_guess", options={"expose"=true})
     * @Method("POST")
     * @return JsonResponse
     */
    public function guessDeclensionAction(Request $request)
    {
        $infinitive = trim($request->request->get('infinitive'));
        $declensions = $this->get('twig.declension')->getDeclensions($infinitive);

        if (!$infinitive || !$declensions) {
            $response = new JsonResponse();
            $response->setData(['status' => 'error']);

            return $response;
        }

        $response = new JsonResponse();
        $response->setData(['status' => 'success', 'declensions' => $declensions]);

        return $response;
    }

    /**
     * Creates a form to delete a Declension entity by id.
     *
     * @param Declension $declension
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Declension $declension)
    {
        return $this->createFormBuilder()
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}

src/TwigDeclensionBundle/Resources/views/Declension/delete.html.twig
{% extends '::base.html.twig' %}
{% form_theme form 'BubnovTwigDeclensionBundle:Form:form_row.html.twig' %}

{% block title %}{{ 'twig-declension.delete' | trans }}{% endblock %}

{% block body -%}
    <h1 class="alert alert-danger">{{ 'twig-declension.delete' | trans }} "{{ entity }}"</h1>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        
        <div class="pull-right">
            <input type="submit" id="_submit" name="_submit" value="{{ 'twig-declension.delete'| trans }}" class="btn btn-danger" />
            <a href="{{ path('admin_twig_declension') }}" id="cancel" class="btn btn-default">
                {{ 'twig-declension.cancel'| trans }}
            </a>
        </div>
    {{ form_end(form) }}
</ul>
{% endblock %}

src/TwigDeclensionBundle/Resources/views/Declension/edit.html.twig
{% extends '::base.html.twig' %}
{% form_theme form 'BubnovTwigDeclensionBundle:Form:form_row.html.twig' %}

{% block title %}{{ 'twig-declension.edit' | trans }}{% endblock %}

{% block body -%}
    <h1>{{ 'twig-declension.edit' | trans }} "{{ entity }}"</h1>
    {{ form_start(form) }}
        {{ form_widget(form) }}

        <div class="pull-right">
            <input type="submit" id="_submit" name="_submit" value="{{ 'twig-declension.save'| trans }}" class="btn btn-success" />
            <a href="{{ path('admin_twig_declension') }}" id="cancel" class="btn btn-default">
                {{ 'twig-declension.cancel'| trans }}
            </a>
        </div>
    {{ form_end(form) }}
</ul>
{% endblock %}

src/TwigDeclensionBundle/Resources/views/Declension/index.html.twig
{% extends '::base.html.twig' %}
{% form_theme form 'BubnovTwigDeclensionBundle:Form:form_row.html.twig' %}

{% block title %}{{ 'twig-declension.index' | trans }}{% endblock %}

{% block body %}
    <h1>{{ 'twig-declension.index' | trans }}</h1>
    
    <div class="pull-right">
        <a class="btn btn-success" id="admin_seometa_new" href="{{ path('admin_twig_declension_new') }}">
            <span class="icon-plus icon-white"></span> {{ 'twig-declension.add' | trans}}
        </a>
    </div>
    <br> 
    
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-primary">{{ 'twig-declension.search' | trans }}</button>
        <a class="btn btn-default" href="{{ path('admin_twig_declension') }}">
            {{ 'twig-declension.find_all' | trans}}
        </a>
    {{ form_end(form) }}
    <separator></separator>

    {% if entities is empty %}
        {{ 'twig-declension.errors.not_found' | trans }}
    {% else %}
    {{ knp_pagination_render(pagination) }}
    <table class="records_list table table-striped">
        <thead>
            <tr>
                <th>{{ 'twig-declension.forms.inf' | trans }}</th>
                <th>{{ 'twig-declension.needs_work' | trans }}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for entity in entities %}
            <tr>
                <td>
                    <a href="{{ path('admin_twig_declension_edit', { 'id': entity.id }) }}">{{ entity }}</a>
                </td>
                <td>
                    {% if entity.needWork %}
                        {{ 'twig-declension.yes' | trans }}
                    {% else %}
                        {{ 'twig-declension.no' | trans }}
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('admin_twig_declension_edit', { 'id': entity.id }) }}" title="{{ 'twig-declension.edit' | trans}}">
                        <i class="icon-pencil"></i>
                    </a>
                    <a href="{{ path('admin_twig_declension_delete', { 'id': entity.id }) }}" title="{{ 'twig-declension.delete' | trans}}">
                        <i class="icon-trash"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {{ knp_pagination_render(pagination) }}
    {% endif %}

{% endblock %}

src/TwigDeclensionBundle/Resources/views/Declension/new.html.twig
{% extends '::base.html.twig' %}
{% form_theme form 'BubnovTwigDeclensionBundle:Form:form_row.html.twig' %}

{% block title %}{{ 'twig-declension.add-declension' | trans }}{% endblock %}

{% block body %}
    <h1>{{ 'twig-declension.add-declension' | trans }}</h1>

    {{ form_start(form) }}

        {{ form_widget(form) }}

        <div class="pull-right">
            <input type="submit" id="_submit" name="_submit" value="{{ 'twig-declension.add'| trans }}" class="btn btn-success" />
            <a href="{{ path('admin_twig_declension') }}" id="cancel" class="btn btn-default">
                {{ 'twig-declension.cancel'| trans }}
            </a>
        </div>
    {{ form_end(form) }}
{% endblock %}